### PR TITLE
Update README.md - Add welcome message in Bulgarian

### PR DESCRIPTION
**Pull request by BorislavSabev**
Just added yet another language to the "welcome header".

Accept it if you deem it fit. :)

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
Greetings @BorislavSabev! Sorry that no-one noticed this for so long; happy for you to ping me about it. I am happy to approve this; the wording is appropriate, and I loved Sofia when I visited for UX Sofia ;-)

Unfortunately, I don't have the necessary privs to merge PRs on this repo. @Rumyra can you do the honors?

**Comment by bsmth** [comment]
Thanks a lot for opening this one. We're not adding any more languages to this header, but you're very welcome to open a PR here to add it to our GitHub README / profile:

https://github.com/mdn/.github/blob/main/profile/README.md

Thank you! 🙏🏻

**Comment by BorislavSabev** [comment]
@bsmth @chrisdavidmills thank you for the help. Here it is: https://github.com/mdn/.github/pull/43

**Comment by bsmth** [comment]
Thanks a lot! Going to close this one as the linked PR is merged now!

**Pull request closed without merging**
